import { Inter } from "next/font/google";
// CSS
import "@/styles/tailwind.css";
import "@/styles/app.css";
// Animation Component
import { PageTransitionComponen } from "./pageTransitionEffect";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PageTransitionComponen>{children}</PageTransitionComponen>
      </body>
    </html>
  );
}
